apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium  # Azure premium SSD
  resources:
    requests:
      storage: 10Gi
